export const SET_TAB = 'SET_TAB';

export const LOAD_TOWN_WHEATHER = 'FETCH_TOWN_WHEATHER';
export const LOAD_TOWN_WHEATHER_FAILED = 'LOAD_TOWN_WHEATHER_FAILED';
export const LOAD_TOWN_WHEATHER_SUCCESS = 'LOAD_TOWN_WHEATHER_SUCCESS';
export const SET_ACTIVE_TOWN_WHEATHER = 'SET_ACTIVE_TOWN_WHEATHER';
export const EDIT_TOWN_WHEATHER = 'EDIT_TOWN_WHEATHER';

export const SORT_TOWNS = 'SORT_TOWNS';
export const MOVE_TOWN = 'MOVE_TOWN';

export const SAVE_INPUT = 'SAVE_INPUT';
export const CLEAR_INPUT = 'CLEAR_INPUT';